<?php

namespace Database\Seeders;

use App\Models\Property;
use Illuminate\Database\Seeder;

class ArushaPropertySeeder extends Seeder
{
    /**
     * Seed real Arusha properties scraped from arushahomes.com (2026-08-13).
     * Source: Arusha Awesome Homes & Properties — real listings, real prices.
     */
    public function run(): void
    {
        $properties = [
        [
            'title' => '08 Apartments for–Rent Burka Estate, Arusha starting from $1200',
            'description' => 'Fully Furnished Apartments for Rent – Burka Estate, Arusha Located in the highly desirable Burka Estate area of Arusha, these eight fully furnished apartments are among the finest residences on the Arusha Airport side and within the entire Burka neighborhood. The exceptional construction quality, modern finishing, spacious layouts, and elegant architectural design make these apartments truly uniqu',
            'city' => 'Arusha',
            'region' => 'Arusha',
            'country' => 'Tanzania',
            'property_type' => 'residential',
            'listing_type' => 'rent',
            'price' => 1200,
            'currency' => 'USD',
            'bedrooms' => null,
            'status' => 'active',
            'is_featured' => false,
            'listed_at' => now()->subDays(12),
            'views_count' => rand(20, 300),
        ],
        [
            'title' => '2-Bedroom Apartment for Daily and Long term renting',
            'description' => 'Ideal for singles, couples, families, or professional expatriates! Located in the peaceful and green Njiro area, just 10km from Arusha Clock Tower, and only 2km from Njiro Container Roundabout, this cozy, well-maintained compound offers four self-contained and fully furnished 2-bedroom apartments – perfect for comfortable living in a serene environment. 2 self-contained bedrooms per apartment',
            'city' => 'Arusha',
            'region' => 'Arusha',
            'country' => 'Tanzania',
            'property_type' => 'residential',
            'listing_type' => 'rent',
            'price' => 100,
            'currency' => 'USD',
            'bedrooms' => 2,
            'status' => 'active',
            'is_featured' => false,
            'listed_at' => now()->subDays(11),
            'views_count' => rand(20, 300),
        ],
        [
            'title' => '4-Bedroom Houses for Rent in Burka.',
            'description' => 'Two beautiful 4-bedroom houses located in Burka South (Burka Coffee area) are now available for rent. These homes offer top-class finishes, a stunning view, and are perfect for a large family seeking comfort, security, and convenience. Spacious lounge with comfortable, high-quality furniture Dining room with an 8-seater dining table',
            'city' => 'Arusha',
            'region' => 'Arusha',
            'country' => 'Tanzania',
            'property_type' => 'residential',
            'listing_type' => 'rent',
            'price' => 2000,
            'currency' => 'USD',
            'bedrooms' => 4,
            'status' => 'active',
            'is_featured' => false,
            'listed_at' => now()->subDays(10),
            'views_count' => rand(20, 300),
        ],
        [
            'title' => '4-Bedroom House for Rent – Boma Siara, Baraa Village',
            'description' => 'A beautiful fully furnished 4-bedroom house is available for rent in Boma Siara, Baraa Village, conveniently located close to the tarmac road. This property is ideal for families looking for a comfortable, move-in-ready home. It is also an excellent option for corporate clients, expatriates, or visitors. Whether you are looking for a family home or a fully furnished property for a short or long st',
            'city' => 'Arusha',
            'region' => 'Arusha',
            'country' => 'Tanzania',
            'property_type' => 'residential',
            'listing_type' => 'rent',
            'price' => 1500,
            'currency' => 'USD',
            'bedrooms' => 4,
            'status' => 'active',
            'is_featured' => false,
            'listed_at' => now()->subDays(9),
            'views_count' => rand(20, 300),
        ],
        [
            'title' => '4-Bedroom House for Rent – Moshono, Arusha',
            'description' => 'A beautiful and spacious 4-bedroom house for rent in Moshono, Arusha, located in a peaceful and desirable residential area. This three-storey home offers generous living spaces, en-suite bedrooms, beautiful views, and a spacious compound—ideal for a family looking for comfort, privacy, and quality living. This house is an excellent choice for a family seeking space, comfort, privacy, security, and',
            'city' => 'Arusha',
            'region' => 'Arusha',
            'country' => 'Tanzania',
            'property_type' => 'residential',
            'listing_type' => 'rent',
            'price' => 1600,
            'currency' => 'USD',
            'bedrooms' => 4,
            'status' => 'active',
            'is_featured' => false,
            'listed_at' => now()->subDays(8),
            'views_count' => rand(20, 300),
        ],
        [
            'title' => '4-Bedroom House for Sale – Njiro, Arusha',
            'description' => 'Located in the highly sought-after Njiro area, just a short distance from Lake Oil Petrol Station and Njiro Lutheran Church, this exceptional home offers comfort, quality, and an excellent location. Designed and owned by a professional civil engineer, the house showcases outstanding construction quality, a practical layout, and attention to detail. This is an excellent home for a family, expatriat',
            'city' => 'Arusha',
            'region' => 'Arusha',
            'country' => 'Tanzania',
            'property_type' => 'residential',
            'listing_type' => 'sale',
            'price' => 180000,
            'currency' => 'USD',
            'bedrooms' => 4,
            'status' => 'active',
            'is_featured' => false,
            'listed_at' => now()->subDays(7),
            'views_count' => rand(20, 300),
        ],
        [
            'title' => '4-Bedroom House for sale in Ngaramtoni-Arusha',
            'description' => 'Charming 4-Bedroom House for Sale in Ngaramtoni – Breathtaking Views of Mount Meru Discover a rare opportunity to own a beautiful 4-bedroom home nestled in the serene hills of Ngaramtoni. Set on a generous 4.25-acre plot, this property offers unmatched panoramic views of Mount Meru and the southeastern expanse of Arusha, a truly peaceful and picturesque setting. The home features a spacious and we',
            'city' => 'Arusha',
            'region' => 'Arusha',
            'country' => 'Tanzania',
            'property_type' => 'residential',
            'listing_type' => 'sale',
            'price' => 670000,
            'currency' => 'USD',
            'bedrooms' => 4,
            'status' => 'active',
            'is_featured' => false,
            'listed_at' => now()->subDays(6),
            'views_count' => rand(20, 300),
        ],
        [
            'title' => '3-Bedroom Bungalow for rent –SakinaUpper Sakina',
            'description' => 'Charming Three-Bedroom Bungalow for rent – Upper Sakina This attractive bungalow is located in a quiet and secure neighborhood in Upper Sakina, approximately 1.5 km from the Moshi–Nairobi tarmac road area opposite Sakina meet factory. The home has a warm and inviting character, featuring beautiful red brick walls and natural wood finishes throughout. It sits within a well-established, mature garde',
            'city' => 'Arusha',
            'region' => 'Arusha',
            'country' => 'Tanzania',
            'property_type' => 'residential',
            'listing_type' => 'rent',
            'price' => 800,
            'currency' => 'USD',
            'bedrooms' => 3,
            'status' => 'active',
            'is_featured' => false,
            'listed_at' => now()->subDays(5),
            'views_count' => rand(20, 300),
        ],
        [
            'title' => '1-Bedroom Cottage for Rent – Sakina, Arusha',
            'description' => 'One-Bedroom Cottage for Rent – Sakina, Arusha A beautifully renovated one-bedroom cottage is now available for rent in a secure compound of six cottages, conveniently located in Sakina, just 3 minutes\' drive from the Oryx Petrol Station on Nairobi Road, approximately halfway between Arusha Town and the New East Africa By-Pass. The compound consists of one-bedroom, two-bedroom, and three-bedroom co',
            'city' => 'Arusha',
            'region' => 'Arusha',
            'country' => 'Tanzania',
            'property_type' => 'residential',
            'listing_type' => 'rent',
            'price' => 200,
            'currency' => 'USD',
            'bedrooms' => 1,
            'status' => 'active',
            'is_featured' => false,
            'listed_at' => now()->subDays(4),
            'views_count' => rand(20, 300),
        ],
        [
            'title' => 'Prime Property for Sale in Njiro – Behind TEMDO, Arusha',
            'description' => 'Prime Property for Sale in Njiro – Behind TEMDO, Arusha An excellent opportunity to own a prime plot located in the vibrant and fast-developing Njiro area, just behind TEMDO and very close to the Arusha Institute of Accountancy. This half-acre (2,000 sqm) plot is ideal for a variety of investment opportunities including: Residential or mixed-use development',
            'city' => 'Arusha',
            'region' => 'Arusha',
            'country' => 'Tanzania',
            'property_type' => 'residential',
            'listing_type' => 'sale',
            'price' => null,
            'currency' => 'USD',
            'bedrooms' => null,
            'status' => 'active',
            'is_featured' => false,
            'listed_at' => now()->subDays(3),
            'views_count' => rand(20, 300),
        ],
        [
            'title' => 'Saba Saba Apartments-Arusha: Rent starting from USD1,200',
            'description' => 'Old meets new at the iconic Saba Saba Hotel grounds, now transformed into modern residential apartments while maintaining the spacious charm of its original layout. Nestled in the heart of Arusha along Simeon Road, Saba Saba Residency offers a variety of elegantly furnished apartments: Studio, One-bedroom, Two-bedroom, and Three-bedroom units—all within a serene, secure, and prime location. Locate',
            'city' => 'Arusha',
            'region' => 'Arusha',
            'country' => 'Tanzania',
            'property_type' => 'residential',
            'listing_type' => 'rent',
            'price' => 1200,
            'currency' => 'USD',
            'bedrooms' => null,
            'status' => 'active',
            'is_featured' => false,
            'listed_at' => now()->subDays(2),
            'views_count' => rand(20, 300),
        ],
        [
            'title' => '2-Bedroom Spacious House for Rent in Sakina',
            'description' => 'Location: Sakina Silent Inn, ArushaRent: USD 350/monthAdditional Charges: USD 50/month (covers water and compound maintenance)Total: USD 400/monthPrice is negotiable and can be paid in Tanzanian Shillings (TSh) based on current exchange rates 2 Bedrooms – including 1 en-suite with in-built wardrobes Spacious Sitting Room and Dining Area',
            'city' => 'Arusha',
            'region' => 'Arusha',
            'country' => 'Tanzania',
            'property_type' => 'residential',
            'listing_type' => 'rent',
            'price' => 350,
            'currency' => 'USD',
            'bedrooms' => 2,
            'status' => 'active',
            'is_featured' => false,
            'listed_at' => now()->subDays(1),
            'views_count' => rand(20, 300),
        ],
        ];

        foreach ($properties as $property) {
            Property::create($property);
        }
    }
}
