<?php

namespace Database\Seeders;

use App\Models\Property;
use Illuminate\Database\Seeder;

class PropertySeeder extends Seeder
{
    public function run(): void
    {
        $properties = [
            [
                'title' => 'Modern 3-Bedroom Apartment in Masaki',
                'description' => 'Beautifully finished 3-bedroom apartment in the heart of Masaki, Dar es Salaam. Features a spacious living area, modern kitchen, balcony with ocean views, borehole water, and backup generator. Walking distance to restaurants, gyms, and the beach.',
                'address_line' => 'Haile Selassie Road, Masaki',
                'city' => 'Dar es Salaam',
                'region' => 'Dar es Salaam',
                'property_type' => 'residential',
                'listing_type' => 'rent',
                'bedrooms' => 3,
                'bathrooms' => 3,
                'building_area' => 180,
                'lot_size' => 400,
                'stories' => 1,
                'year_built' => 2022,
                'price' => 2500000,
                'currency' => 'TZS',
                'amenities' => ['security', 'water_tank', 'generator', 'gym', 'parking'],
                'status' => 'active',
                'is_featured' => true,
                'latitude' => -6.7500,
                'longitude' => 39.2833,
            ],
            [
                'title' => 'Spacious 4-Bedroom House in Mikocheni',
                'description' => 'Family home with 4 bedrooms, 3 bathrooms, and a large compound in quiet Mikocheni. Includes servant quarters, water storage, and solar backup. Ideal for families and expatriates.',
                'address_line' => 'Mikocheni B',
                'city' => 'Dar es Salaam',
                'region' => 'Dar es Salaam',
                'property_type' => 'residential',
                'listing_type' => 'rent',
                'bedrooms' => 4,
                'bathrooms' => 3,
                'building_area' => 220,
                'lot_size' => 800,
                'stories' => 1,
                'year_built' => 2020,
                'price' => 3500000,
                'currency' => 'TZS',
                'amenities' => ['security', 'water_tank', 'solar', 'servant_quarters', 'parking'],
                'status' => 'active',
                'is_featured' => true,
                'latitude' => -6.7450,
                'longitude' => 39.2600,
            ],
            [
                'title' => 'Prime Commercial Plot in Kijitonyama',
                'description' => 'Corner commercial plot in Kijitonyama, perfect for offices, showrooms, or retail. Zoned for mixed commercial use with road frontage on both sides. Title deed available.',
                'address_line' => 'Kijitonyama, Kinondoni',
                'city' => 'Dar es Salaam',
                'region' => 'Dar es Salaam',
                'property_type' => 'land',
                'listing_type' => 'sale',
                'lot_size' => 1200,
                'price' => 450000000,
                'currency' => 'TZS',
                'amenities' => ['road_frontage', 'title_deed'],
                'status' => 'active',
                'is_featured' => true,
                'latitude' => -6.7730,
                'longitude' => 39.2440,
            ],
            [
                'title' => '3-Bedroom House in Njiro, Arusha',
                'description' => 'Well-maintained 3-bedroom house in a secure gated community in Njiro, Arusha. Features a garden, parking for 2 cars, and proximity to international schools and shopping centers.',
                'address_line' => 'Njiro, Arusha',
                'city' => 'Arusha',
                'region' => 'Arusha',
                'property_type' => 'residential',
                'listing_type' => 'sale',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'building_area' => 160,
                'lot_size' => 600,
                'stories' => 1,
                'year_built' => 2019,
                'price' => 280000000,
                'currency' => 'TZS',
                'amenities' => ['gated_community', 'garden', 'parking', 'water_tank'],
                'status' => 'active',
                'is_featured' => false,
                'latitude' => -3.3833,
                'longitude' => 36.6833,
            ],
            [
                'title' => 'Office Space in the CBD, Dar es Salaam',
                'description' => 'Modern office space in the city center, 120 m², ready for occupancy. Includes meeting rooms, backup power, high-speed internet, and 24/7 security. Ideal for startups and SMEs.',
                'address_line' => 'Samora Avenue, CBD',
                'city' => 'Dar es Salaam',
                'region' => 'Dar es Salaam',
                'property_type' => 'commercial',
                'listing_type' => 'rent',
                'building_area' => 120,
                'price' => 4000000,
                'currency' => 'TZS',
                'amenities' => ['security', 'generator', 'internet', 'conference_room'],
                'status' => 'active',
                'is_featured' => false,
                'latitude' => -6.8150,
                'longitude' => 39.2920,
            ],
            [
                'title' => 'Beachfront Villa in Kiwengwa, Zanzibar',
                'description' => 'Stunning beachfront villa in Kiwengwa with 5 bedrooms, private pool, and direct beach access. Turnkey investment property with strong rental income potential. Includes staff quarters.',
                'address_line' => 'Kiwengwa, Unguja',
                'city' => 'Kiwengwa',
                'region' => 'Zanzibar',
                'property_type' => 'residential',
                'listing_type' => 'sale',
                'bedrooms' => 5,
                'bathrooms' => 5,
                'building_area' => 350,
                'lot_size' => 1000,
                'stories' => 2,
                'year_built' => 2021,
                'price' => 950000000,
                'currency' => 'TZS',
                'amenities' => ['pool', 'beach_access', 'staff_quarters', 'security', 'solar'],
                'status' => 'active',
                'is_featured' => true,
                'latitude' => -5.9900,
                'longitude' => 39.3450,
            ],
        ];

        foreach ($properties as $property) {
            Property::create(array_merge($property, [
                'listed_at' => now()->subDays(rand(1, 20)),
                'views_count' => rand(10, 500),
            ]));
        }
    }
}
