<?php

namespace Database\Seeders;

use App\Models\Property;
use Illuminate\Database\Seeder;

class RealtorPropertySeeder extends Seeder
{
    /**
     * Seed real Arusha properties scraped from arusharealtor.co.tz (2026-08-13).
     */
    public function run(): void
    {
        $properties = [
        [
            'title' => '145.4 Acres Farm for Sale in Makuyuni, Arusha – Prime Roadside Agricultural Investment',
            'description' => 'This exceptional 145.4-acre farm for sale in Makuyuni, Arusha offers a rare opportunity to secure large-scale agricultural land in one of Tanzania’s strategic growth corridors. Located just 5km from Makuyuni Junction and directly next to the main road, the property provides outstanding accessibility for farming operations, transportation, and future development projects. Whether you are an agricultural investor, commercial farmer, or land banker looking for high-potential property in Arusha, thi',
            'city' => 'Arusha',
            'region' => 'Arusha',
            'country' => 'Tanzania',
            'property_type' => 'land',
            'listing_type' => 'sale',
            'price' => 350000000,
            'currency' => 'TZS',
            'bedrooms' => null,
            'status' => 'active',
            'is_featured' => false,
            'listed_at' => now()->subDays(12),
            'views_count' => rand(30, 400),
        ],
        [
            'title' => '2.25-Acre Hilltop Plot for Sale in AFCON City',
            'description' => 'Prime 2.25-acre hilltop plot for sale in AFCON City, Arusha, offering an excellent opportunity for residential development, a private estate, or a high-value investment. The property is located approximately 400 metres from the main road, providing convenient access while maintaining the privacy and elevated setting of a hilltop location. Its generous size and position make it suitable for a spacious private residence, luxury homes, or other carefully planned developments. This is a strategicall',
            'city' => 'Arusha',
            'region' => 'Arusha',
            'country' => 'Tanzania',
            'property_type' => 'land',
            'listing_type' => 'sale',
            'price' => 165000000,
            'currency' => 'TZS',
            'bedrooms' => null,
            'status' => 'active',
            'is_featured' => false,
            'listed_at' => now()->subDays(11),
            'views_count' => rand(30, 400),
        ],
        [
            'title' => '3-Bedroom House for Sale in Sakina – Arusha',
            'description' => 'Discover this charming 3-bedroom home for sale in Sakina, Arusha, offering a perfect balance of comfort, privacy, and convenience. Built on a 900-square-meter compound, the property provides plenty of outdoor space for family living or future expansion. Located just 1.5 km from Arusha Meat–Sakina, the home enjoys easy access to schools, shops, and main transport routes while maintaining a peaceful residential atmosphere. Helping You Buy &amp; Sell Property in Arusha, Tanzania Local Expertise. Ho',
            'city' => 'Arusha',
            'region' => 'Arusha',
            'country' => 'Tanzania',
            'property_type' => 'residential',
            'listing_type' => 'sale',
            'price' => 180000000,
            'currency' => 'TZS',
            'bedrooms' => 3,
            'status' => 'active',
            'is_featured' => false,
            'listed_at' => now()->subDays(10),
            'views_count' => rand(30, 400),
        ],
        [
            'title' => '3-Bedroom House for Sale – Njiro Block F, Arusha',
            'description' => 'This 3-bedroom house is located in the well-established and highly desirable Njiro Block F area of Arusha, known for its good neighborhood and easy accessibility. The property sits on a spacious 800 square meter compound, offering ample outdoor space for future expansion, landscaping, parking, or additional development. The house requires renovation, making it an excellent opportunity for buyers looking to customize the home to their taste or investors seeking a property with strong value apprec',
            'city' => 'Arusha',
            'region' => 'Arusha',
            'country' => 'Tanzania',
            'property_type' => 'residential',
            'listing_type' => 'sale',
            'price' => 90000000,
            'currency' => 'TZS',
            'bedrooms' => 3,
            'status' => 'active',
            'is_featured' => false,
            'listed_at' => now()->subDays(9),
            'views_count' => rand(30, 400),
        ],
        [
            'title' => '5-Bedroom House for Sale in Njiro, Arusha',
            'description' => 'Discover this beautiful 5-bedroom house for sale in Njiro, Arusha, located just 700 m from the main road. Built on a spacious 1,800 sqm compound, this home offers a modern layout, large garden, and scenic views of Mount Meru — ideal for family living or long-term investment. Helping You Buy &amp; Sell Property in Arusha, Tanzania Local Expertise. Honest Service. Email: info@arusharealtor.co.tz',
            'city' => 'Arusha',
            'region' => 'Arusha',
            'country' => 'Tanzania',
            'property_type' => 'residential',
            'listing_type' => 'sale',
            'price' => 450000000,
            'currency' => 'TZS',
            'bedrooms' => 5,
            'status' => 'active',
            'is_featured' => false,
            'listed_at' => now()->subDays(8),
            'views_count' => rand(30, 400),
        ],
        [
            'title' => '61-Acre Farm for Sale – Usa River, Arusha',
            'description' => 'A 61-acre farm is available for sale in Usa River, Arusha, offering an excellent opportunity for agricultural investment, residential development, or a private estate. The property is conveniently located next to Dolly Estate and approximately 4.4 km from the main tarmac road, providing a balance of accessibility and privacy. The farm has a valid title deed, providing secure ownership, and water is available within the property, making it suitable for a range of agricultural and development acti',
            'city' => 'Arusha',
            'region' => 'Arusha',
            'country' => 'Tanzania',
            'property_type' => 'land',
            'listing_type' => 'sale',
            'price' => 60000000,
            'currency' => 'TZS',
            'bedrooms' => null,
            'status' => 'active',
            'is_featured' => false,
            'listed_at' => now()->subDays(7),
            'views_count' => rand(30, 400),
        ],
        [
            'title' => '6-Acre Hill Plot for Sale – Olmoti, Arusha',
            'description' => 'Discover a rare opportunity to own prime elevated land in Olmoti, Arusha, offering beautiful panoramic views and excellent potential for both private development and long-term investment. The property comprises 6 acres of scenic hill land, strategically located approximately 6 km from the AFCON Stadium. Its elevated position provides a peaceful setting with expansive views of the surrounding landscape, while its proximity to Arusha\'s growing infrastructure makes it an attractive investment oppor',
            'city' => 'Arusha',
            'region' => 'Arusha',
            'country' => 'Tanzania',
            'property_type' => 'land',
            'listing_type' => 'sale',
            'price' => 150000000,
            'currency' => 'TZS',
            'bedrooms' => null,
            'status' => 'active',
            'is_featured' => false,
            'listed_at' => now()->subDays(6),
            'views_count' => rand(30, 400),
        ],
        [
            'title' => '7 ACRES FARM FOR SALE – KISONGO, ARUSHA',
            'description' => 'A fantastic 7-acre property with a Title Deed, located in the fast-growing Kisongo area of Arusha ideal for farming, residential development, or a strategic investment project. &#x1f4cd; Location: Kisongo, Arusha&#x1f4d0; Size: 7 Acres&#x1f4dc; Title Deed: Available&#x1f6e3;&#xfe0f; Distance from main road: Approx. 800 metres&#x1f4a7; Water: Available&#x26a1; Electricity: Available &#x1f3e1; Existing facilities include:• A house• Cattle sheds• Chicken houses• A rainwater harvesting/storage pit &',
            'city' => 'Arusha',
            'region' => 'Arusha',
            'country' => 'Tanzania',
            'property_type' => 'land',
            'listing_type' => 'sale',
            'price' => 750000000,
            'currency' => 'TZS',
            'bedrooms' => null,
            'status' => 'active',
            'is_featured' => false,
            'listed_at' => now()->subDays(5),
            'views_count' => rand(30, 400),
        ],
        [
            'title' => '5 Acre Plot for Sale at Mateves - Arusha',
            'description' => 'An excellent investment opportunity in the fast-growing area of Mateves, Arusha. This prime property offers a total of 5 acres available for sale, strategically positioned just 2 km from the Dodoma–Arusha Road and only 700 meters from the road to AFCON. The location provides convenient access while maintaining a peaceful environment ideal for development. Each acre is priced at TZS 185 Million, making it suitable for developers, investors, and individuals looking to secure land in a high-potenti',
            'city' => 'Arusha',
            'region' => 'Arusha',
            'country' => 'Tanzania',
            'property_type' => 'land',
            'listing_type' => 'sale',
            'price' => 185000000,
            'currency' => 'TZS',
            'bedrooms' => null,
            'status' => 'active',
            'is_featured' => false,
            'listed_at' => now()->subDays(4),
            'views_count' => rand(30, 400),
        ],
        [
            'title' => 'AFCON CITY 1 ESTATE PLOTS FOR SALE',
            'description' => 'Welcome to AFCON CITY 1  Estate.Just 1KM from the new state-of-the-art AFCON Stadium and only 4KM from the Dodoma–Arusha highway, this emerging gem is set to become one of Arusha’s most attractive investment hubs. Whether you\'re a homeowner in the making or a savvy investor looking for the next big thing, these plots offer more than just land—they offer unmatched potential. AFCON CITY 1 Estate features both residential and commercial plots, starting from 412 square meters and above, designed to ',
            'city' => 'Arusha',
            'region' => 'Arusha',
            'country' => 'Tanzania',
            'property_type' => 'land',
            'listing_type' => 'sale',
            'price' => 27000,
            'currency' => 'TZS',
            'bedrooms' => null,
            'status' => 'active',
            'is_featured' => false,
            'listed_at' => now()->subDays(3),
            'views_count' => rand(30, 400),
        ],
        [
            'title' => 'Bondeni City – Premium Residential & Commercial Plots for Sale in Oljoro, Arusha',
            'description' => 'Welcome to Bondeni City, a modern and well-planned gated community located in Oljoro, Arusha. This prime development is strategically positioned at the same location as the new bus stand currently under construction and just minutes away from the upcoming AFCON Stadium — making it one of the most promising investment locations in the city. Bondeni City offers both residential and commercial plots, giving buyers flexibility whether they are building a family home or investing in business property',
            'city' => 'Arusha',
            'region' => 'Arusha',
            'country' => 'Tanzania',
            'property_type' => 'land',
            'listing_type' => 'sale',
            'price' => 50000,
            'currency' => 'TZS',
            'bedrooms' => null,
            'status' => 'active',
            'is_featured' => false,
            'listed_at' => now()->subDays(2),
            'views_count' => rand(30, 400),
        ],
        [
            'title' => '3.5 Acres Prime Land for Sale in Mateves, Arusha – Near Arusha Airport & AFCON Stadium',
            'description' => 'Looking for prime land for sale in Arusha? This exclusive 3.5-acre property in Mateves, Arusha offers a rare opportunity to secure land in one of the city’s fastest-growing investment corridors. Strategically located just 1.5km from the Arusha–Dodoma Road, this property combines accessibility, prestige, and long-term capital appreciation potential. Positioned near Arusha Airport and along the route to the upcoming AFCON Stadium, this area is rapidly transforming into a prime residential and comm',
            'city' => 'Arusha',
            'region' => 'Arusha',
            'country' => 'Tanzania',
            'property_type' => 'land',
            'listing_type' => 'sale',
            'price' => 170000000,
            'currency' => 'TZS',
            'bedrooms' => null,
            'status' => 'active',
            'is_featured' => false,
            'listed_at' => now()->subDays(1),
            'views_count' => rand(30, 400),
        ],
        ];

        foreach ($properties as $property) {
            Property::create($property);
        }
    }
}
